#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import argparse
import crypt
import subprocess

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("username")
    parser.add_argument("password")
    args = parser.parse_args()

    ret = 0
    try:
        ciphertext = crypt.crypt(args.password, crypt.METHOD_SHA512)
        if crypt.crypt(args.password, ciphertext) != ciphertext:
            raise ValueError('Error in generating password')
        cmd = "useradd -g mail -p '{0}' -s /sbin/nologin {1}".format(ciphertext, args.username)
        print cmd
        subprocess.check_call(cmd, shell=True)

        cmd = "mkdir /home/{0}/mail".format(args.username)
        print cmd
        subprocess.check_call(cmd, shell=True)

        cmd = "chown -R {0}.mail /home/{0}/mail".format(args.username)
        print cmd
        subprocess.check_call(cmd, shell=True)

    except Exception as e:
        ret = -1
        print e
    return ret

if __name__ == '__main__':
    sys.exit(main())
